name: Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image:  ghcr.io/cheetah-game-platform/rust-builder-x86_64-unknown-linux-musl:0.0.2
    steps:
      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - uses: actions/checkout@v3
      - name: Check
        run: |           
           cargo outdated -d 1 --exit-code 1
           cargo +nightly udeps
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
